spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
  jmx:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /product-service

logging:
  level:
    tyt.product: INFO
  file:
    name: logs/product.log

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true