spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jmx:
    enabled: true
server:
  port: 8081
logging:
  level:
    tyt.product: INFO
  file:
    name: logs/product.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka