spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: 8086
  jetty:
    max-http-response-header-size: 16384
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
security:
  jwt:
    secret-key: TNDbOVzVNAzfbxBaqEkGRuY/bV5mMPjv5ZNL0kWuqMc=