spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  main:
    lazy-initialization: true

server:
  port: 8086
  jetty:
    max-http-response-header-size: 16384
  http2:
    enabled: true
  reactive:
    session:
      timeout: 10m

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
security:
  jwt:
    secret-key: TNDbOVzVNAzfbxBaqEkGRuY/bV5mMPjv5ZNL0kWuqMc=

management:
  endpoints:
    web:
      exposure:
        include: health,info