spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tytDB
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true