spring:
  application:
    name: record-service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
  jmx:
    enabled: true
  thymeleaf:
    mode: HTML
    cache: true
server:
  port: 8083

logging:
  level:
    tyt.record: INFO
  file:
    name: logs/record.log

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true