spring:
  application:
    name: auth-service
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
  security:
    jwt:
      secret-key: TNDbOVzVNAzfbxBaqEkGRuY/bV5mMPjv5ZNL0kWuqMc=
      expiration: 8640000

logging:
  level:
    tyt.management: INFO
  file:
    name: logs/auth.log

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true