spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:aVeryStrongSecretKeyForJWT}
      expiration: 8640000
server:
  port: 8087