package tyt.product.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.Data;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * This is a base entity class that other entities can extend.
 * It includes common fields such as id, createdAt, createdBy, updatedAt, updatedBy.
 * It implements Serializable interface for the objects to be able to be converted into a byte stream.
 * It is annotated with @Data from Lombok to auto-generate boilerplate code like getters, setters, equals, hashCode and toString methods.
 * It is annotated with @MappedSuperclass to allow JPA to include properties from this class into child entity classes.
 */
@Data
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity implements Serializable {

    /**
     * This is the primary key for the entity.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    /**
     * This field represents the creation time of the entity.
     */
    @CreatedDate
    @JsonFormat(pattern = "dd-MM-yyyy HH:mm:ss")
    @Column(updatable = false)
    protected LocalDateTime createdAt;

    /**
     * This field represents the user who created the entity.
     */

    @CreatedBy
    protected String createdBy;

    /**
     * This field represents the last update time of the entity.
     */
    @LastModifiedDate
    @JsonFormat(pattern = "dd-MM-yyyy HH:mm:ss")
    @Column(insertable = false)
    protected LocalDateTime updatedAt;

    /**
     * This field represents the user who last updated the entity.
     */
    @LastModifiedBy
    @Column(insertable = false)
    protected String updatedBy;
}