package tyt.product.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Data;

import java.io.Serializable;

/**
 * This is a base entity class that other entities can extend.
 * It includes common fields such as id, createdAt, createdBy, updatedAt, updatedBy.
 * It implements Serializable interface for the objects to be able to be converted into a byte stream.
 * It is annotated with @Data from Lombok to auto-generate boilerplate code like getters, setters, equals, hashCode and toString methods.
 * It is annotated with @MappedSuperclass to allow JPA to include properties from this class into child entity classes.
 */
@Data
@MappedSuperclass
public abstract class BaseEntity implements Serializable {

    /**
     * This is the primary key for the entity.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    /**
     * This field represents the creation time of the entity.
     */
    protected String createdAt;

    /**
     * This field represents the user who created the entity.
     */
    protected String createdBy;

    /**
     * This field represents the last update time of the entity.
     */
    protected String updatedAt;

    /**
     * This field represents the user who last updated the entity.
     */
    protected String updatedBy;
}