package tyt.sales.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Data;

import java.io.Serializable;

/**
 * This is a base entity class that other entity classes can extend.
 * It includes common properties like id.
 * It implements Serializable interface which makes it eligible for being persisted.
 * It is annotated with @Data from Lombok to auto-generate boilerplate code like getters, setters, equals, hashCode and toString methods.
 * It is annotated with @MappedSuperclass to indicate that this class is intended to be used with entity inheritance.
 */
@Data
@MappedSuperclass
public abstract class BaseEntity implements Serializable {

    /**
     * This is the primary key for the entity.
     * It is auto-generated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;
}