spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jmx:
    enabled: true
#  cache:
#    type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379

server:
  port: 8082