spring:
  application:
    name: sales-service
  jpa:
    hibernate:
      ddl-auto: update
  jmx:
    enabled: true
server:
  port: 8082
  servlet:
    context-path: /sales-service
logging:
  level:
    tyt.sales: INFO
  file:
    name: logs/sales.log
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true