spring:
  application:
    name: sales-service
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jmx:
    enabled: true
server:
  port: 8082
  servlet:
    context-path: /sales-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    tyt.sales: INFO
  file:
    name: logs/sales.log